export const PAYMENT_ADD_ITEM="PAYMENT_ADD_ITEM";

export const FAIL_PAYMENT="FAIL_PAYMENT";
export const LOAD_PAYMENT="LOAD_PAYMENT";
export const GET_USER_PAYMENTS="GET_USER_PAYMENTS";
export const CLEAR_ERRORS="CLEAR_ERRORS";



export const GET_PAYMENTS="GET_PAYMENTS";
export const GET_PAYMENT="GET_PAYMENT";